# Generated by Django 4.1.3 on 2022-11-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(default='other', max_length=100),
        ),
    ]
