# Generated by Django 4.1.3 on 2022-12-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_billing_user_city_user_country_user_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.IntegerField(default=50),
        ),
    ]
