# Generated by Django 4.1.3 on 2022-12-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_genral_category',
            field=models.CharField(default='other', max_length=100),
        ),
    ]
