# Generated by Django 4.1.3 on 2022-12-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_wishlist_wishlist_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist_flag',
        ),
        migrations.AddField(
            model_name='product',
            name='wishlist_flag',
            field=models.BooleanField(default=False),
        ),
    ]
