from django.urls import path
from .import views

urlpatterns = [
    path('',views.index,name="index"),
    path('seller_index/',views.seller_index,name="seller_index"),
    path('about/',views.about,name="about"),
    path('cart/',views.cart,name="cart"),
    path('checkout/',views.checkout,name="checkout"),
    path('contact_us/',views.contact_us,name="contact_us"),
    path('my_account/',views.my_account,name="my_account"),
    path('service/',views.service,name="service"),
    path('shop_detail/',views.shop_detail,name="shop_detail"),
    path('shop/',views.shop,name="shop"),
    path('wishlist/',views.wishlist,name="wishlist"),
    path('login/',views.login,name="login"),
    path('logout/',views.logout,name="logout"),
    path('signup/',views.signup,name="signup"),
    path('profile/',views.profile,name="profile"),
    path('change_password/',views.change_password,name="change_password"),
    path('forgote_password/',views.forgote_password,name="forgote_password"),
    path('otp/',views.otp,name="otp"),
    path('new_password/',views.new_password,name="new_password"),
    path('add_product/',views.add_product,name="add_product"),
    path('view_product/',views.view_product,name="view_product"),
    path('detail_product/<int:pk>/',views.detail_product,name="detail_product"),
    path('edit_product/<int:pk>/',views.edit_product,name="edit_product"),
    path('delete_product/<int:pk>/',views.delete_product,name="delete_product"),
    path('all/',views.all,name="all"),
    path('seller_chenge_password/',views.seller_chenge_password,name="seller_chenge_password"),
    path('seller_edit_profile/',views.seller_edit_profile,name="seller_edit_profile"),
    path('buyer_product_detail/<int:pk>/',views.buyer_product_detail,name="buyer_product_detail"),
    path('add_to_wishlist/<int:pk>/',views.add_to_wishlist,name="add_to_wishlist"),
    path('show_wishlist/',views.show_wishlist,name="show_wishlist"),
    path('remove_from_wishlist/<int:pk>/',views.remove_from_wishlist,name="remove_from_wishlist"),
    path('add_to_cart/<int:pk>/',views.add_to_cart,name="add_to_cart"),
    path('change_qty/<int:pk>/',views.change_qty,name="change_qty"),
    path('shipping_method/',views.shipping_method,name="shipping_method"),
    path('remove_from_cart/<int:pk>/',views.remove_from_cart,name="remove_from_cart"),
    path('billing_address/',views.billing_address,name="billing_address"),
    path('category/<str:name>/',views.category,name="category"),
    path('search/',views.search,name="search"),
    path('top_search/',views.top_search,name="top_search"),
    path('top_category/<str:name>/',views.top_category,name="top_category"),
    path('range_category/',views.range_category,name="range_category"),
    path('price/',views.price,name="price"),
    path('brand/',views.brand,name="brand"),
    path('pay/',views.initiate_payment, name='pay'),
    path('callback/',views.callback, name='callback'),
    path('ajax/validate_email/',views.validate_login,name="validate_email"),
    path('ajax/validate_mobile/',views.validate_mobile,name="validate_mobile"),
    path('my_order/',views.my_order,name="my_order"),
   
]
